name: godartffi
version: 1.2.3
description: >-
  Testing Go Dart FFI
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
  args: ^1.6.0
dev_dependencies:
  