name: interop
description: Dart gRPC interoperability test suite.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.5.2
  async: ^2.2.0
  collection: ^1.14.11
  grpc:
    path: ../
  protobuf: ^0.13.12

dev_dependencies:
  test: ^1.6.4
